import type { DashboardData, LatestPrediction, LeaderboardRow, ModelMetricRow, TickerHistoryRow } from "./dashboardData";

const generatedAt = "2026-06-22T12:00:00.000Z";

const leaderboard: LeaderboardRow[] = [
  {
    generated_at: generatedAt,
    window: "all",
    evaluation_window: "all",
    prediction_horizon: "all",
    model_name: "TimesFM",
    model_slug: "timesfm",
    model_type: "Time Series",
    mae: 5.12,
    directional_accuracy: 0.61,
    winkler_score: 18.4,
    prediction_count: 128,
    scored_count: 128,
    rank: 1,
  },
  {
    generated_at: generatedAt,
    window: "all",
    evaluation_window: "all",
    prediction_horizon: "all",
    model_name: "Random Forest",
    model_slug: "random-forest",
    model_type: "Classic ML",
    mae: 6.03,
    directional_accuracy: 0.56,
    winkler_score: 21.7,
    prediction_count: 128,
    scored_count: 128,
    rank: 2,
  },
  {
    generated_at: generatedAt,
    window: "all",
    evaluation_window: "all",
    prediction_horizon: "1w",
    model_name: "TimesFM",
    model_slug: "timesfm",
    model_type: "Time Series",
    mae: 2.18,
    directional_accuracy: 0.64,
    winkler_score: 8.9,
    prediction_count: 42,
    scored_count: 42,
    rank: 1,
  },
  {
    generated_at: generatedAt,
    window: "all",
    evaluation_window: "all",
    prediction_horizon: "1m",
    model_name: "Chronos-2",
    model_slug: "chronos-2",
    model_type: "Time Series",
    mae: 7.31,
    directional_accuracy: 0.58,
    winkler_score: 25.2,
    prediction_count: 31,
    scored_count: 31,
    rank: 1,
  },
  {
    generated_at: generatedAt,
    window: "all",
    evaluation_window: "all",
    prediction_horizon: "3m",
    model_name: "Linear Regression",
    model_slug: "linear-regression",
    model_type: "Classic ML",
    mae: null,
    directional_accuracy: null,
    winkler_score: null,
    prediction_count: 0,
    scored_count: 0,
    rank: null,
  },
  {
    generated_at: generatedAt,
    window: "all",
    evaluation_window: "all",
    prediction_horizon: "1y",
    model_name: "Baseline",
    model_slug: "baseline",
    model_type: "Benchmark",
    mae: null,
    directional_accuracy: null,
    winkler_score: null,
    prediction_count: 0,
    scored_count: 0,
    rank: null,
  },
];

const latestPredictions: LatestPrediction[] = [
  {
    generated_at: generatedAt,
    prediction_id: "AAPL:2026-06-22:2026-06-29:1w:timesfm",
    prediction_date: "2026-06-22",
    target_date: "2026-06-29",
    prediction_horizon: "1w",
    ticker: "AAPL",
    model_name: "TimesFM",
    model_slug: "timesfm",
    reference_close: 198.42,
    predicted_return: 0.018,
    predicted_close: 201.99,
    predicted_close_lower: 193.12,
    predicted_close_upper: 210.24,
    interval_level: 0.8,
    winkler_score: null,
    reasoning_summary: null,
    model_metadata: { source: "fallback" },
  },
  {
    generated_at: generatedAt,
    prediction_id: "NVDA:2026-06-22:2026-07-22:1m:chronos-2",
    prediction_date: "2026-06-22",
    target_date: "2026-07-22",
    prediction_horizon: "1m",
    ticker: "NVDA",
    model_name: "Chronos-2",
    model_slug: "chronos-2",
    reference_close: 144.31,
    predicted_return: -0.012,
    predicted_close: 142.58,
    predicted_close_lower: 126.44,
    predicted_close_upper: 161.82,
    interval_level: 0.8,
    winkler_score: null,
    reasoning_summary: null,
    model_metadata: { source: "fallback" },
  },
];

const tickerHistory: TickerHistoryRow[] = [
  {
    generated_at: generatedAt,
    prediction_id: "AAPL:2026-06-15:2026-06-22:1w:timesfm",
    ticker: "AAPL",
    date: "2026-06-22",
    prediction_date: "2026-06-15",
    target_date: "2026-06-22",
    prediction_horizon: "1w",
    actual_close: 198.42,
    model_name: "TimesFM",
    model_slug: "timesfm",
    predicted_close: 197.63,
    predicted_close_lower: 190.04,
    predicted_close_upper: 205.22,
    interval_level: 0.8,
    predicted_return: 0.006,
    actual_return: 0.01,
    winkler_score: 15.18,
    reasoning_summary: null,
  },
];

const modelMetrics: ModelMetricRow[] = leaderboard
  .filter((row) => row.rank != null)
  .map((row) => ({
    generated_at: row.generated_at,
    window: row.window,
    evaluation_window: row.evaluation_window,
    prediction_horizon: row.prediction_horizon,
    model_name: row.model_name,
    model_slug: row.model_slug,
    mae: row.mae,
    directional_accuracy: row.directional_accuracy,
    winkler_score: row.winkler_score,
    prediction_count: row.prediction_count,
    scored_count: row.scored_count,
  }));

export const fallbackDashboardData: DashboardData = {
  leaderboard,
  modelMetrics,
  latestPredictions,
  tickerHistory,
  metadata: {
    generated_at: generatedAt,
    latest_price_date: "2026-06-22",
    next_target_date: null,
    latest_prediction_date: "2026-06-22",
    ticker_count: 2,
    model_count: 4,
    prediction_count: latestPredictions.length,
    scored_count: modelMetrics.reduce((total, row) => total + row.prediction_count, 0),
    data_source: "fallback",
    last_pipeline_status: "success",
  },
  hasSupabaseConfig: false,
};
