import type {
  DashboardData,
  LatestPrediction,
  LatestUserPrediction,
  LeaderboardRow,
  ModelMetricRow,
  TickerCloseSnapshot,
  TickerHistoryRow,
  TickerProfile,
  UserLeaderboardRow,
  UserTickerLeaderboardRow,
} from "./dashboardData";

const generatedAt = "2026-06-22T12:00:00.000Z";

const leaderboard: LeaderboardRow[] = [
  {
    generated_at: generatedAt,
    window: "all",
    evaluation_window: "all",
    prediction_horizon: "all",
    model_name: "TimesFM",
    model_slug: "timesfm",
    model_type: "Time Series",
    mae: 5.12,
    mape: 0.0312,
    directional_accuracy: 0.61,
    winkler_score: 18.4,
    prediction_count: 128,
    scored_count: 128,
    rank: 1,
  },
  {
    generated_at: generatedAt,
    window: "all",
    evaluation_window: "all",
    prediction_horizon: "all",
    model_name: "Random Forest",
    model_slug: "random-forest",
    model_type: "Classic ML",
    mae: 6.03,
    mape: 0.0395,
    directional_accuracy: 0.56,
    winkler_score: 21.7,
    prediction_count: 128,
    scored_count: 128,
    rank: 2,
  },
  {
    generated_at: generatedAt,
    window: "all",
    evaluation_window: "all",
    prediction_horizon: "1w",
    model_name: "TimesFM",
    model_slug: "timesfm",
    model_type: "Time Series",
    mae: 2.18,
    mape: 0.0148,
    directional_accuracy: 0.64,
    winkler_score: 8.9,
    prediction_count: 42,
    scored_count: 42,
    rank: 1,
  },
  {
    generated_at: generatedAt,
    window: "all",
    evaluation_window: "all",
    prediction_horizon: "1m",
    model_name: "Chronos-2",
    model_slug: "chronos-2",
    model_type: "Time Series",
    mae: 7.31,
    mape: 0.047,
    directional_accuracy: 0.58,
    winkler_score: 25.2,
    prediction_count: 31,
    scored_count: 31,
    rank: 1,
  },
  {
    generated_at: generatedAt,
    window: "all",
    evaluation_window: "all",
    prediction_horizon: "3m",
    model_name: "Linear Regression",
    model_slug: "linear-regression",
    model_type: "Classic ML",
    mae: null,
    mape: null,
    directional_accuracy: null,
    winkler_score: null,
    prediction_count: 0,
    scored_count: 0,
    rank: null,
  },
  {
    generated_at: generatedAt,
    window: "all",
    evaluation_window: "all",
    prediction_horizon: "1y",
    model_name: "Baseline",
    model_slug: "baseline",
    model_type: "Benchmark",
    mae: null,
    mape: null,
    directional_accuracy: null,
    winkler_score: null,
    prediction_count: 0,
    scored_count: 0,
    rank: null,
  },
];

const latestPredictions: LatestPrediction[] = [
  {
    generated_at: generatedAt,
    prediction_id: "AAPL:2026-06-22:2026-06-29:1w:timesfm",
    prediction_date: "2026-06-22",
    target_date: "2026-06-29",
    prediction_horizon: "1w",
    ticker: "AAPL",
    model_name: "TimesFM",
    model_slug: "timesfm",
    reference_close: 198.42,
    predicted_return: 0.018,
    predicted_close: 201.99,
    predicted_close_lower: 193.12,
    predicted_close_upper: 210.24,
    interval_level: 0.8,
    winkler_score: null,
    reasoning_summary: null,
    model_metadata: { source: "fallback" },
  },
  {
    generated_at: generatedAt,
    prediction_id: "NVDA:2026-06-22:2026-07-22:1m:chronos-2",
    prediction_date: "2026-06-22",
    target_date: "2026-07-22",
    prediction_horizon: "1m",
    ticker: "NVDA",
    model_name: "Chronos-2",
    model_slug: "chronos-2",
    reference_close: 144.31,
    predicted_return: -0.012,
    predicted_close: 142.58,
    predicted_close_lower: 126.44,
    predicted_close_upper: 161.82,
    interval_level: 0.8,
    winkler_score: null,
    reasoning_summary: null,
    model_metadata: { source: "fallback" },
  },
];

const userLeaderboard: UserLeaderboardRow[] = [
  {
    generated_at: generatedAt,
    window: "all",
    evaluation_window: "all",
    prediction_horizon: "all",
    user_id: "fallback-user-1",
    username: "AdaAlpha",
    avatar_style: "adventurer-neutral",
    avatar_seed: "ada-alpha",
    avatar_options: {
      eyebrowsVariant: "variant04",
      eyesVariant: "variant10",
      glassesVariant: "variant02",
      glassesProbability: 100,
      mouthVariant: "variant12",
      backgroundColor: "f2d3b1",
      scale: 1.1,
      rotate: 0,
    },
    mae: 4.82,
    mape: 0.0284,
    directional_accuracy: 0.64,
    prediction_count: 14,
    scored_count: 14,
    rank: 1,
  },
  {
    generated_at: generatedAt,
    window: "all",
    evaluation_window: "all",
    prediction_horizon: "all",
    user_id: "fallback-user-2",
    username: "GraceGain",
    avatar_style: "adventurer-neutral",
    avatar_seed: "grace-gain",
    avatar_options: {
      eyebrowsVariant: "variant09",
      eyesVariant: "variant03",
      glassesVariant: "variant01",
      glassesProbability: 0,
      mouthVariant: "variant20",
      backgroundColor: "ecad80",
      scale: 1,
      rotate: -2,
    },
    mae: 5.35,
    mape: 0.0341,
    directional_accuracy: 0.57,
    prediction_count: 12,
    scored_count: 12,
    rank: 2,
  },
  {
    generated_at: generatedAt,
    window: "all",
    evaluation_window: "all",
    prediction_horizon: "1w",
    user_id: "fallback-user-1",
    username: "AdaAlpha",
    avatar_style: "adventurer-neutral",
    avatar_seed: "ada-alpha",
    avatar_options: {
      eyebrowsVariant: "variant04",
      eyesVariant: "variant10",
      glassesVariant: "variant02",
      glassesProbability: 100,
      mouthVariant: "variant12",
      backgroundColor: "f2d3b1",
      scale: 1.1,
      rotate: 0,
    },
    mae: 2.11,
    mape: 0.0127,
    directional_accuracy: 0.71,
    prediction_count: 7,
    scored_count: 7,
    rank: 1,
  },
];

const latestUserPredictions: LatestUserPrediction[] = [
  {
    generated_at: generatedAt,
    prediction_id: "fallback-user-prediction-aapl",
    user_id: "fallback-user-1",
    username: "AdaAlpha",
    avatar_style: "adventurer-neutral",
    avatar_seed: "ada-alpha",
    avatar_options: userLeaderboard[0].avatar_options,
    prediction_date: "2026-06-22",
    target_date: "2026-06-29",
    prediction_horizon: "1w",
    ticker: "AAPL",
    reference_close: 198.42,
    predicted_return: 0.023,
    predicted_close: 202.98,
  },
  {
    generated_at: generatedAt,
    prediction_id: "fallback-user-prediction-nvda",
    user_id: "fallback-user-2",
    username: "GraceGain",
    avatar_style: "adventurer-neutral",
    avatar_seed: "grace-gain",
    avatar_options: userLeaderboard[1].avatar_options,
    prediction_date: "2026-06-22",
    target_date: "2026-07-22",
    prediction_horizon: "1m",
    ticker: "NVDA",
    reference_close: 144.31,
    predicted_return: 0.034,
    predicted_close: 149.22,
  },
];

const userTickerLeaderboard: UserTickerLeaderboardRow[] = [
  {
    ...userLeaderboard[1],
    ticker: "AAPL",
    prediction_horizon: "all",
    mae: 3.95,
    mape: 0.0246,
    directional_accuracy: 0.67,
    prediction_count: 4,
    scored_count: 4,
    rank: 1,
  },
  {
    ...userLeaderboard[0],
    ticker: "AAPL",
    prediction_horizon: "all",
    mae: 4.24,
    mape: 0.0268,
    directional_accuracy: 0.6,
    prediction_count: 5,
    scored_count: 5,
    rank: 2,
  },
  {
    ...userLeaderboard[0],
    ticker: "AAPL",
    prediction_horizon: "1w",
    mae: 2.11,
    mape: 0.0127,
    directional_accuracy: 0.71,
    prediction_count: 2,
    scored_count: 2,
    rank: 1,
  },
];

const tickerHistory: TickerHistoryRow[] = [
  {
    generated_at: generatedAt,
    prediction_id: "AAPL:2026-06-15:2026-06-22:1w:timesfm",
    ticker: "AAPL",
    date: "2026-06-22",
    prediction_date: "2026-06-15",
    target_date: "2026-06-22",
    prediction_horizon: "1w",
    actual_close: 198.42,
    model_name: "TimesFM",
    model_slug: "timesfm",
    predicted_close: 197.63,
    predicted_close_lower: 190.04,
    predicted_close_upper: 205.22,
    interval_level: 0.8,
    predicted_return: 0.006,
    actual_return: 0.01,
    winkler_score: 15.18,
    reasoning_summary: null,
  },
];

export const fallbackTickerProfiles: Record<string, TickerProfile> = {
  AAPL: {
    ticker: "AAPL",
    company_name: "Apple Inc.",
    logo_data_url: null,
    sector: "Technology",
    industry: "Consumer Electronics",
    business_summary:
      "Apple designs consumer electronics, software, and services including iPhone, Mac, iPad, Apple Watch, and digital subscription offerings. Its ecosystem blends hardware, operating systems, apps, cloud services, and retail support.",
    as_of_date: "2026-06-22",
    source: "fallback",
  },
  NVDA: {
    ticker: "NVDA",
    company_name: "NVIDIA Corporation",
    logo_data_url: null,
    sector: "Technology",
    industry: "Semiconductors",
    business_summary:
      "NVIDIA builds graphics processors, accelerated computing platforms, and AI infrastructure for gaming, data centers, professional visualization, and automotive markets.",
    as_of_date: "2026-06-22",
    source: "fallback",
  },
  SPY: {
    ticker: "SPY",
    company_name: "SPDR S&P 500 ETF Trust",
    logo_data_url: null,
    sector: "ETF",
    industry: "Large Blend",
    business_summary:
      "SPY is an exchange-traded fund designed to track the S&P 500 Index, giving broad exposure to large-cap U.S. equities.",
    as_of_date: "2026-06-22",
    source: "fallback",
  },
};

export const fallbackTickerCloseSnapshots: Record<string, TickerCloseSnapshot> = {
  AAPL: {
    ticker: "AAPL",
    date: "2026-06-22",
    close: 198.42,
    previous_date: "2026-06-21",
    previous_close: 196.46,
    change: 1.96,
    change_percent: 0.009976585564491497,
  },
  NVDA: {
    ticker: "NVDA",
    date: "2026-06-22",
    close: 144.31,
    previous_date: "2026-06-21",
    previous_close: 145.02,
    change: -0.71,
    change_percent: -0.004895876430837109,
  },
  SPY: {
    ticker: "SPY",
    date: "2026-06-22",
    close: 548.72,
    previous_date: "2026-06-21",
    previous_close: 546.39,
    change: 2.33,
    change_percent: 0.004264354220429457,
  },
};

const tickerAssets = Object.values(fallbackTickerProfiles).map((profile) => ({
  ticker: profile.ticker,
  logo_data_url: profile.logo_data_url,
  company_name: profile.company_name,
}));

const modelMetrics: ModelMetricRow[] = leaderboard
  .filter((row) => row.rank != null)
  .map((row) => ({
    generated_at: row.generated_at,
    window: row.window,
    evaluation_window: row.evaluation_window,
    prediction_horizon: row.prediction_horizon,
    model_name: row.model_name,
    model_slug: row.model_slug,
    mae: row.mae,
    mape: row.mape,
    directional_accuracy: row.directional_accuracy,
    winkler_score: row.winkler_score,
    prediction_count: row.prediction_count,
    scored_count: row.scored_count,
  }));

export const fallbackDashboardData: DashboardData = {
  leaderboard,
  userLeaderboard,
  userTickerLeaderboard,
  modelMetrics,
  latestPredictions,
  latestUserPredictions,
  tickerAssets,
  tickerHistory,
  metadata: {
    generated_at: generatedAt,
    latest_price_date: "2026-06-22",
    next_target_date: null,
    latest_prediction_date: "2026-06-22",
    ticker_count: 2,
    model_count: 4,
    prediction_count: latestPredictions.length,
    scored_count: modelMetrics.reduce((total, row) => total + row.prediction_count, 0),
    data_source: "fallback",
    last_pipeline_status: "success",
  },
  hasSupabaseConfig: false,
};
