import type { LeaderboardRow, LatestPrediction } from "../api/dashboardData";

export type ModelInfo = {
  slug: string;
  name: string;
  type: ModelType;
  description: string;
  learnMore?: string;
};

export type ModelType = "Benchmark" | "Machine Learning" | "Foundation Model" | "Toy (LLM)";

const descriptions: Record<string, Omit<ModelInfo, "slug" | "name">> = {
  baseline: {
    type: "Benchmark",
    description:
      "The simplest possible forecasting model. It assumes the price will remain unchanged over the selected prediction horizon. While intentionally naive, it provides an essential benchmark that every other model should strive to outperform.",
    learnMore: "https://otexts.com/fpp3/accuracy.html",
  },

  "linear-regression": {
    type: "Machine Learning",
    description:
      "A classic statistical model that learns a weighted relationship between historical market features and future returns. Fast, highly interpretable, and often surprisingly competitive, it serves as a strong baseline for more sophisticated machine learning models.",
    learnMore:
      "https://scikit-learn.org/stable/modules/linear_model.html#ordinary-least-squares",
  },

  "random-forest": {
    type: "Machine Learning",
    description:
      "An ensemble of decision trees that combines hundreds of independent predictions into a single forecast. By averaging many trees, Random Forest can capture nonlinear market relationships while reducing overfitting compared to an individual decision tree.",
    learnMore:
      "https://scikit-learn.org/stable/modules/ensemble.html#forest",
  },

  timesfm: {
    type: "Foundation Model",
    description:
      "Google's pretrained Time Series Foundation Model. Instead of being trained specifically on stock prices, TimesFM has learned forecasting patterns from millions of real-world time series, allowing it to generate forecasts for new datasets without additional training.",
    learnMore: "https://github.com/google-research/timesfm",
  },

  "chronos-2": {
    type: "Foundation Model",
    description:
      "Amazon's next-generation transformer-based forecasting model. Chronos-2 uses in-context learning to generate zero-shot forecasts from historical data, enabling accurate predictions across many different types of time series without retraining.",
    learnMore: "https://github.com/amazon-science/chronos-forecasting",
  },

  "warren-buffbot": {
    type: "Toy (LLM)",
    description:
      "A large language model prompted to think like a value investor inspired by Warren Buffett. Rather than using traditional forecasting algorithms, Buffbot analyzes historical market data through natural language reasoning to produce its own prediction.",
  },
};

export const searchableModels: ModelInfo[] = [
  ["baseline", "Baseline"],
  ["linear-regression", "Linear Regression"],
  ["random-forest", "Random Forest"],
  ["timesfm", "TimesFM"],
  ["chronos-2", "Chronos-2"],
  ["warren-buffbot", "Warren Buffbot"],
].map(([slug, name]) => getModelInfo(slug, name));

export function getModelInfo(slug: string, fallbackName?: string): ModelInfo {
  const fallback = fallbackName ?? titleFromSlug(slug);
  return {
    slug,
    name: fallback,
    ...(descriptions[slug] ?? {
      type: "Classic ML",
      description: "A project model trained on engineered historical market features.",
      inputs: "Uses the dashboard-approved feature contract generated by the Python pipeline.",
    }),
  };
}

// Maps both the new frontend vocabulary and the legacy pipeline/database
// vocabulary (registry.py emits "Classic ML" / "Time Series" / "Toy LLM" /
// "Benchmark") onto the current ModelType enum. Without this, legacy values fall
// through to the default and every model renders a "Machine Learning" badge.
const modelTypeAliases: Record<string, ModelType> = {
  benchmark: "Benchmark",
  baseline: "Benchmark",
  "machine learning": "Machine Learning",
  "classic ml": "Machine Learning",
  "foundation model": "Foundation Model",
  "time series": "Foundation Model",
  "toy (llm)": "Toy (LLM)",
  "toy llm": "Toy (LLM)",
};

export function normalizeModelType(value?: string): ModelType {
  const mapped = value ? modelTypeAliases[value.trim().toLowerCase()] : undefined;
  return mapped ?? "Machine Learning";
}

export function modelTypeColor(type: ModelType) {
  if (type === "Benchmark") {
    return "black";
  }
  if (type === "Toy (LLM)") {
    return "orange";
  }
  if (type === "Foundation Model") {
    return "teal";
  }
  return "gray";
}

export function getModelNames(
  leaderboard: LeaderboardRow[],
  predictions: LatestPrediction[],
) {
  const names = new Map<string, string>();

  leaderboard.forEach((row) => names.set(row.model_slug, row.model_name));
  predictions.forEach((row) => names.set(row.model_slug, row.model_name));

  return names;
}

function titleFromSlug(slug: string) {
  return slug
    .split("-")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}
