import type { LeaderboardRow, LatestPrediction } from "../api/dashboardData";

export type ModelInfo = {
  slug: string;
  name: string;
  type: "Baseline" | "Statistical" | "Toy LLM";
  description: string;
};

const descriptions: Record<string, Omit<ModelInfo, "slug" | "name">> = {
  baseline: {
    type: "Baseline",
    description: "Naive baseline model that always predicts zero return for the selected horizon.",
  },
  "linear-regression": {
    type: "Statistical",
    description: "Fits a simple linear relationship between engineered market features and horizon-specific returns.",
  },
  ridge: {
    type: "Statistical",
    description: "Uses linear regression with L2 regularization to steady correlated feature weights.",
  },
  lasso: {
    type: "Statistical",
    description: "Uses linear regression with L1 regularization, which can shrink weaker features toward zero.",
  },
  "random-forest": {
    type: "Statistical",
    description: "Compares the linear models against a small nonlinear tree ensemble.",
  },
  "warren-buffbot": {
    type: "Toy LLM",
    description: "A LLM (Gemini flash 1.5 or Groq) that's been instructed to make predictions using value-oriented investment principles.",
  },
};

export function getModelInfo(slug: string, fallbackName?: string): ModelInfo {
  const fallback = fallbackName ?? titleFromSlug(slug);
  return {
    slug,
    name: fallback,
    ...(descriptions[slug] ?? {
      type: "Statistical",
      description: "A project model trained on engineered historical market features.",
      inputs: "Uses the dashboard-approved feature contract generated by the Python pipeline.",
    }),
  };
}

export function getModelNames(
  leaderboard: LeaderboardRow[],
  predictions: LatestPrediction[],
) {
  const names = new Map<string, string>();

  leaderboard.forEach((row) => names.set(row.model_slug, row.model_name));
  predictions.forEach((row) => names.set(row.model_slug, row.model_name));

  return names;
}

function titleFromSlug(slug: string) {
  return slug
    .split("-")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}
