import type { LeaderboardRow, LatestPrediction } from "../api/dashboardData";

export type ModelInfo = {
  slug: string;
  name: string;
  type: ModelType;
  description: string;
};

export type ModelType = "Benchmark" | "Classic ML" | "Time Series" | "Toy LLM";

const descriptions: Record<string, Omit<ModelInfo, "slug" | "name">> = {
  baseline: {
    type: "Benchmark",
    description: "Naive baseline model that always predicts zero return for the selected horizon.",
  },
  "linear-regression": {
    type: "Classic ML",
    description: "Fits a simple linear relationship between engineered market features and horizon-specific returns.",
  },
  "random-forest": {
    type: "Classic ML",
    description: "Compares the linear models against a small nonlinear tree ensemble.",
  },
  timesfm: {
    type: "Time Series",
    description: "Uses Google's pretrained TimesFM time-series model to produce horizon-specific price paths and intervals.",
  },
  "chronos-2": {
    type: "Time Series",
    description: "Uses Amazon Chronos-2, a pretrained time-series foundation model, for zero-shot horizon predictions.",
  },
  "warren-buffbot": {
    type: "Toy LLM",
    description: "An LLM instructed to make predictions using value-oriented investment principles.",
  },
};

export function getModelInfo(slug: string, fallbackName?: string): ModelInfo {
  const fallback = fallbackName ?? titleFromSlug(slug);
  return {
    slug,
    name: fallback,
    ...(descriptions[slug] ?? {
      type: "Classic ML",
      description: "A project model trained on engineered historical market features.",
      inputs: "Uses the dashboard-approved feature contract generated by the Python pipeline.",
    }),
  };
}

export function normalizeModelType(value?: string): ModelType {
  if (value === "Benchmark" || value === "Classic ML" || value === "Time Series" || value === "Toy LLM") {
    return value;
  }
  return "Classic ML";
}

export function modelTypeColor(type: ModelType) {
  if (type === "Benchmark") {
    return "gray";
  }
  if (type === "Toy LLM") {
    return "yellow";
  }
  if (type === "Time Series") {
    return "teal";
  }
  return "green";
}

export function getModelNames(
  leaderboard: LeaderboardRow[],
  predictions: LatestPrediction[],
) {
  const names = new Map<string, string>();

  leaderboard.forEach((row) => names.set(row.model_slug, row.model_name));
  predictions.forEach((row) => names.set(row.model_slug, row.model_name));

  return names;
}

function titleFromSlug(slug: string) {
  return slug
    .split("-")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}
