-- Dashboard user leaderboard rows are generated by the Python dashboard refresh.
-- Keep those projection rows intact across privacy toggles and enforce privacy
-- through RLS instead, so returning public users do not disappear until the next
-- full refresh rebuilds the ranked tables.

drop policy if exists "Allow public dashboard user leaderboard reads"
on public.dashboard_user_leaderboard;
create policy "Allow public dashboard user leaderboard reads"
on public.dashboard_user_leaderboard
for select
to anon, authenticated
using (
    exists (
        select 1
        from public.user_profiles profile
        where profile.user_id = dashboard_user_leaderboard.user_id
            and profile.is_public = true
    )
);

drop policy if exists "Allow public dashboard user ticker leaderboard reads"
on public.dashboard_user_ticker_leaderboard;
create policy "Allow public dashboard user ticker leaderboard reads"
on public.dashboard_user_ticker_leaderboard
for select
to anon, authenticated
using (
    exists (
        select 1
        from public.user_profiles profile
        where profile.user_id = dashboard_user_ticker_leaderboard.user_id
            and profile.is_public = true
    )
);

drop policy if exists "Allow public dashboard latest user prediction reads"
on public.dashboard_latest_user_predictions;
create policy "Allow public dashboard latest user prediction reads"
on public.dashboard_latest_user_predictions
for select
to anon, authenticated
using (
    exists (
        select 1
        from public.user_profiles profile
        where profile.user_id = dashboard_latest_user_predictions.user_id
            and profile.is_public = true
    )
);

drop policy if exists "Allow public leaderboard snapshot reads"
on public.user_leaderboard_rank_snapshots;
create policy "Allow public leaderboard snapshot reads"
on public.user_leaderboard_rank_snapshots
for select
to anon, authenticated
using (
    is_public
    and exists (
        select 1
        from public.user_profiles profile
        where profile.user_id = user_leaderboard_rank_snapshots.user_id
            and profile.is_public = true
    )
);

drop policy if exists "Allow public leaderboard movement reads"
on public.dashboard_user_leaderboard_movement;
create policy "Allow public leaderboard movement reads"
on public.dashboard_user_leaderboard_movement
for select
to anon, authenticated
using (
    exists (
        select 1
        from public.user_profiles profile
        where profile.user_id = dashboard_user_leaderboard_movement.user_id
            and profile.is_public = true
    )
);

drop policy if exists "Allow public nearby rival reads"
on public.dashboard_user_nearby_rivals;
create policy "Allow public nearby rival reads"
on public.dashboard_user_nearby_rivals
for select
to anon, authenticated
using (
    exists (
        select 1
        from public.user_profiles profile
        where profile.user_id = dashboard_user_nearby_rivals.user_id
            and profile.is_public = true
    )
    and exists (
        select 1
        from public.user_profiles rival_profile
        where rival_profile.user_id = dashboard_user_nearby_rivals.rival_user_id
            and rival_profile.is_public = true
    )
);

drop policy if exists "Allow public ticker specialty reads"
on public.public_user_ticker_specialties;
create policy "Allow public ticker specialty reads"
on public.public_user_ticker_specialties
for select
to anon, authenticated
using (
    exists (
        select 1
        from public.user_profiles profile
        where profile.user_id = public_user_ticker_specialties.user_id
            and profile.is_public = true
    )
);

create or replace function public.refresh_dashboard_user_leaderboards()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    leaderboard_count integer := 0;
    ticker_count integer := 0;
begin
    delete from public.dashboard_user_leaderboard
    where generated_at is not null;

    with latest_public_score as (
        select max(score.scored_at) as scored_at
        from public.user_prediction_scores score
        join public.user_profiles profile
            on profile.user_id = score.user_id
        where profile.is_public = true
    ),
    metric_windows as (
        select *
        from (
            values
                ('7d'::text, 7::integer),
                ('30d'::text, 30::integer),
                ('90d'::text, 90::integer),
                ('all'::text, null::integer)
        ) as window_values(evaluation_window, window_days)
    ),
    expanded_scores as (
        select
            metric_window.evaluation_window,
            horizon.prediction_horizon,
            score.user_id,
            profile.display_username as username,
            coalesce(profile.avatar_style, 'adventurer-neutral') as avatar_style,
            coalesce(profile.avatar_seed, profile.user_id::text) as avatar_seed,
            coalesce(profile.avatar_options, '{}'::jsonb) as avatar_options,
            score.absolute_error,
            score.absolute_pct_error,
            score.direction_correct
        from public.user_prediction_scores score
        join public.user_profiles profile
            on profile.user_id = score.user_id
        cross join metric_windows metric_window
        cross join lateral (
            values (score.prediction_horizon), ('all'::text)
        ) as horizon(prediction_horizon)
        cross join latest_public_score latest
        where profile.is_public = true
            and (
                metric_window.window_days is null
                or score.scored_at >= latest.scored_at - ((metric_window.window_days - 1) * interval '1 day')
            )
    ),
    metrics as (
        select
            evaluation_window,
            prediction_horizon,
            user_id,
            username,
            avatar_style,
            avatar_seed,
            avatar_options,
            avg(absolute_error) as mae,
            avg(absolute_pct_error) as mape,
            avg(direction_correct::double precision) as directional_accuracy,
            count(*)::integer as scored_count
        from expanded_scores
        group by
            evaluation_window,
            prediction_horizon,
            user_id,
            username,
            avatar_style,
            avatar_seed,
            avatar_options
    ),
    ranked as (
        select
            metrics.*,
            rank() over (
                partition by evaluation_window, prediction_horizon
                order by
                    mape,
                    mae,
                    directional_accuracy desc,
                    scored_count desc,
                    lower(username),
                    user_id
            ) as leaderboard_rank
        from metrics
    )
    insert into public.dashboard_user_leaderboard (
        generated_at,
        evaluation_window,
        prediction_horizon,
        user_id,
        username,
        avatar_style,
        avatar_seed,
        avatar_options,
        mae,
        mape,
        directional_accuracy,
        scored_count,
        rank
    )
    select
        now(),
        evaluation_window,
        prediction_horizon,
        user_id,
        username,
        avatar_style,
        avatar_seed,
        avatar_options,
        mae,
        mape,
        directional_accuracy,
        scored_count,
        leaderboard_rank
    from ranked;

    get diagnostics leaderboard_count = row_count;

    delete from public.dashboard_user_ticker_leaderboard
    where generated_at is not null;

    with latest_public_score as (
        select max(score.scored_at) as scored_at
        from public.user_prediction_scores score
        join public.user_profiles profile
            on profile.user_id = score.user_id
        where profile.is_public = true
    ),
    metric_windows as (
        select *
        from (
            values
                ('7d'::text, 7::integer),
                ('30d'::text, 30::integer),
                ('90d'::text, 90::integer),
                ('all'::text, null::integer)
        ) as window_values(evaluation_window, window_days)
    ),
    expanded_scores as (
        select
            score.ticker,
            metric_window.evaluation_window,
            horizon.prediction_horizon,
            score.user_id,
            profile.display_username as username,
            coalesce(profile.avatar_style, 'adventurer-neutral') as avatar_style,
            coalesce(profile.avatar_seed, profile.user_id::text) as avatar_seed,
            coalesce(profile.avatar_options, '{}'::jsonb) as avatar_options,
            score.absolute_error,
            score.absolute_pct_error,
            score.direction_correct
        from public.user_prediction_scores score
        join public.user_profiles profile
            on profile.user_id = score.user_id
        cross join metric_windows metric_window
        cross join lateral (
            values (score.prediction_horizon), ('all'::text)
        ) as horizon(prediction_horizon)
        cross join latest_public_score latest
        where profile.is_public = true
            and (
                metric_window.window_days is null
                or score.scored_at >= latest.scored_at - ((metric_window.window_days - 1) * interval '1 day')
            )
    ),
    metrics as (
        select
            ticker,
            evaluation_window,
            prediction_horizon,
            user_id,
            username,
            avatar_style,
            avatar_seed,
            avatar_options,
            avg(absolute_error) as mae,
            avg(absolute_pct_error) as mape,
            avg(direction_correct::double precision) as directional_accuracy,
            count(*)::integer as scored_count
        from expanded_scores
        group by
            ticker,
            evaluation_window,
            prediction_horizon,
            user_id,
            username,
            avatar_style,
            avatar_seed,
            avatar_options
    ),
    ranked as (
        select
            metrics.*,
            rank() over (
                partition by ticker, evaluation_window, prediction_horizon
                order by
                    mape,
                    mae,
                    directional_accuracy desc,
                    scored_count desc,
                    lower(username),
                    user_id
            ) as leaderboard_rank
        from metrics
    )
    insert into public.dashboard_user_ticker_leaderboard (
        generated_at,
        ticker,
        evaluation_window,
        prediction_horizon,
        user_id,
        username,
        avatar_style,
        avatar_seed,
        avatar_options,
        mae,
        mape,
        directional_accuracy,
        scored_count,
        rank
    )
    select
        now(),
        ticker,
        evaluation_window,
        prediction_horizon,
        user_id,
        username,
        avatar_style,
        avatar_seed,
        avatar_options,
        mae,
        mape,
        directional_accuracy,
        scored_count,
        leaderboard_rank
    from ranked;

    get diagnostics ticker_count = row_count;
    return leaderboard_count + ticker_count;
end;
$$;

create or replace function public.remove_private_user_dashboard_rows()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if old.is_public is distinct from new.is_public then
        perform public.refresh_dashboard_user_leaderboards();
        perform public.refresh_dashboard_latest_user_predictions();

        if new.is_public = true then
            update public.user_leaderboard_rank_snapshots
            set is_public = true
            where user_id = new.user_id;
        end if;
    end if;

    return new;
end;
$$;

update public.user_leaderboard_rank_snapshots snapshot
set is_public = true
from public.user_profiles profile
where profile.user_id = snapshot.user_id
    and profile.is_public = true
    and snapshot.is_public = false;

grant execute on function public.refresh_dashboard_user_leaderboards()
to service_role;

select public.refresh_dashboard_user_leaderboards();
